apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-v6j4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componentb-devfile-sample-go-basic-private-devfile-nested-v6j4
    app.kubernetes.io/part-of: mc-golang-nested
  name: componentb-devfile-sample-go-basic-private-devfile-nested-v6j4
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: componentb-devfile-sample-go-basic-private-devfile-nested-v6j4
status:
  loadBalancer: {}
